BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS cms_access (
  email text PRIMARY KEY CHECK (email = lower(email)),
  auth_user_id text UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  is_owner boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz
);

INSERT INTO cms_access (email, name, is_active, is_owner)
VALUES ('pedro@productpedro.com', 'Pedro Conchas', true, true)
ON CONFLICT (email) DO UPDATE
  SET name = EXCLUDED.name,
      is_active = true,
      is_owner = true,
      updated_at = now();

CREATE TABLE IF NOT EXISTS cms_documents (
  key text PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cms_projects (
  id text PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  subtitle text,
  venue text,
  location text,
  photographer text,
  position integer NOT NULL CHECK (position > 0),
  published boolean NOT NULL DEFAULT false,
  featured boolean NOT NULL DEFAULT false,
  featured_position integer,
  home_shape text NOT NULL DEFAULT 'square',
  home_cover_image_id text,
  cover_image_id text NOT NULL,
  preview_image_count integer NOT NULL DEFAULT 5 CHECK (preview_image_count BETWEEN 1 AND 12),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cms_projects_position_unique UNIQUE (position) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS cms_project_images (
  id text PRIMARY KEY,
  project_id text NOT NULL REFERENCES cms_projects(id) ON DELETE CASCADE,
  src text NOT NULL,
  alt text NOT NULL,
  width integer NOT NULL CHECK (width > 0),
  height integer NOT NULL CHECK (height > 0),
  position integer NOT NULL CHECK (position > 0),
  focal_x numeric(5,4),
  focal_y numeric(5,4),
  crop_tolerance text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, position)
);

CREATE INDEX IF NOT EXISTS cms_project_images_project_id_idx
  ON cms_project_images (project_id, position);

CREATE TABLE IF NOT EXISTS leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  celebration text NOT NULL,
  event_date date,
  venue text,
  guest_count integer CHECK (guest_count IS NULL OR guest_count > 0),
  moodboard_url text,
  notes text,
  status text NOT NULL DEFAULT 'new',
  is_read boolean NOT NULL DEFAULT false,
  email_status text NOT NULL DEFAULT 'not_configured',
  internal_email_id text,
  client_email_id text
);

CREATE INDEX IF NOT EXISTS leads_created_at_idx
  ON leads (created_at DESC);

COMMIT;
